baseURL = "http://example.com/"
languageCode = "en-us"
title = "DATAVA Consulting"
theme = "minimal"

[params]
    description = "Data | Visualization | Analytics"
    accent = "black"
    showBorder = true
    font = "Cormorant Garamond" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    
    
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
    
[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jlebeau@datavaconsulting.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/justlebeau/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jle_beau/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4
    
[[menu.icon]]
    url = "https://www.upwork.com/freelancers/~010a9c857e6806301a"
    name = "user-circle"
    weight = 5
