---
title: "Enhanced MAP Reports"
description: "This project shows MAP reports designed for easy use by teachers.  The reports are designed to retrieve information quickly without logging into the MAP system."
tags: ["r", "MAP"]
weight: 2
draft: false
---

The MAP (Measures of Academic Progress) testing system is an amazing tool for measuring student growth in certain subjects.  Their reporting system for the data also includes a variety of ways to understand student data and to make comparisons.  

However, for schools that use the MAP testing system, the reporting can be challenging for international partners that do not have relevant "norms" for their country.  Many times quick comparison is needed by teachers to understand how their class is performing compared to other students, countries, or regions.  For this reason, these enhanced MAP reports were designed by Datava Consulting to allow teachers easy access to important information.  These reports have been used in all grade levels and assist not only in informing teachers but engaging them is using MAP data for their classroom.

Below is an example report of fake MAP data to demonstrate the use of a this report.  There are several tables of summary data comparing classes to international and country averages.  Additionally, tables have been provided to separate out the scores of students in special education.  Lastly, a table at the bottom includes all the individual scores.  This table allows for filtering, copying, and pasting of data into a spreadsheet program for easy manipulation. 

If you are interested in using these reports for your teachers, send us an email (link above) and we will be in touch shortly.  

<iframe src="https://justlebeau.github.io/MAP_ex.html" embedded=true style="border: 5px solid black; position:absolute; top:510px; left:0; right:0; bottom:0; width:100%; height:100%"</iframe>